// src/component/molecule/timer/AddNewTimerCounter.svelte
<button
  on:click
  class="grid place-items-center p-4 gap-12 h- border-2 border-blue-100 rounded-lg w-96 cursor-pointer text-blue-400  transition-shadow hover:bg-slate-700 active:bg-slate-900 shadow-md shadow-blue-200 hover:shadow-xl hover:shadow-blue-200 active:shadow active:shadow-blue-200 min-h-[40rem]">
  <span class="text-9xl self-end">⏲️</span>
  <span
    class="text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-pink-500 to-violet-500 self-start">
    New Timer
  </span>
</button>

// src/components/molecule/timer/AddNewTimerCounter.tsx
interface Props {
  onNewTimer: () => void;
}

export default function AddNewTimerCounter({ onNewTimer }: Props) {
  return (
    <button
      onClick={onNewTimer}
      className="grid place-items-center p-4 gap-12 border-2 border-blue-100 rounded-lg w-96 cursor-pointer text-blue-400 transition-shadow hover:bg-slate-700 active:bg-slate-900 shadow-md shadow-blue-200 hover:shadow-xl hover:shadow-blue-200 active:shadow active:shadow-blue-200 min-h-[40rem]"
    >
      <span className="text-9xl self-end">⏲️</span>
      <span className="text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-pink-500 to-violet-500 self-start">
        New Timer
      </span>
    </button>
  );
}
