// src/component/organism/timer-grid/TimerSkeletonGrid.svelte
<script lang="ts">
  import TimerSkeleton from "$component/molecule/timer/TimerSkeleton.svelte";

  export let timerSkeletonCount = 9;
</script>

<style>
  div {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(24rem, 1fr));
    gap: 1rem;
    justify-items: center;
  }
</style>

<div class="py-8">
  {#each Array(timerSkeletonCount)
    .fill(null)
    .map((element, index) => {
      return index + 1;
    }) as skeletonIndex}
    <TimerSkeleton />
  {/each}
</div>

// src/components/organism/timer-grid/TimerSkeletonGrid.tsx
import TimerSkeleton from "@/components/molecule/timer/TimerSkeleton";

interface Props {
  timerSkeletonCount?: number;
}

export default function TimerSkeletonGrid({ timerSkeletonCount = 9 }: Props) {
  return (
    <div
      className="py-8"
      style={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(24rem, 1fr))",
        gap: "1rem",
        justifyItems: "center",
      }}
    >
      {Array.from({ length: timerSkeletonCount }, (_, i) => (
        <TimerSkeleton key={i} />
      ))}
    </div>
  );
}
