// src/components/organism/timer-grid/TimersGrid.tsx
"use client";

import type { ActorRefFrom } from "xstate";
import type { timerCounterMachine } from "@/components/molecule/timer/timer-counter/TimerCounter";
import TimerCounterComponent from "@/components/molecule/timer/timer-counter/TimerCounterComponent";
import AddNewTimerCounter from "@/components/molecule/timer/AddNewTimerCounter";

interface Props {
    timers: ActorRefFrom<typeof timerCounterMachine>[];
    onNewTimerCreated: () => void;
}

export default function TimersGrid({ timers, onNewTimerCreated }: Props) {
    return (
        <div
            style={{
                display: "grid",
                gap: "1rem",
                gridTemplateColumns: "repeat(auto-fill, minmax(24rem, 1fr))",
                justifyItems: "center",
                alignItems: "stretch",
            }}
        >
            {timers.map((timer) => (
                <TimerCounterComponent key={timer.id} timer={timer} />
            ))}
            <AddNewTimerCounter onNewTimer={onNewTimerCreated} />
        </div>
    );
}

// src/components/organism/timer-grid/TimersGrid.svelte
<script lang="ts">
  import AddNewTimerCounter from "$components/molecule/timer/AddNewTimerCounter.svelte";
  import type { timerCounterMachine } from "$components/molecule/timer/timer-counter/TimerCounter";
  import TimerCounter from "$components/molecule/timer/timer-counter/TimerCounter.svelte";
  import type { ActorRefFrom } from "xstate";
  import { createEventDispatcher } from "svelte";

  const dispatch = createEventDispatcher();

  export let timers: ActorRefFrom<typeof timerCounterMachine>[];
</script>

<div>
  {#each timers as timer (timer.id)}
    <TimerCounter {timer} />
  {/each}
  <AddNewTimerCounter on:click={() => dispatch("newTimerCreated")} />
</div>

<style>
  div {
    display: grid;
    gap: 1rem;
    grid-template-columns: repeat(auto-fill, minmax(24rem, 1fr));
    justify-items: center;
    align-items: stretch;
  }
</style>
