// src/components/molecule/timer/timer-counter/TimerCounter.svelte
<script lang="ts">
  import TimerDisplay from "$components/atom/display/TimerDisplay.svelte";
  import Divider from "$components/atom/divider/Divider.svelte";
  import Counter from "$components/molecule/counter/Counter.svelte";
  import type { ActorRefFrom } from "xstate";
  import TimerControllerCluster from "../TimerControllerCluster.svelte";
  import TimerSelectButtonCluster from "../TimerSelectButtonCluster.svelte";
  import type { timerCounterMachine } from "$components/molecule/timer/timer-counter/TimerCounter";
  import TimerLabel from "$components/atom/input/TimerLabel.svelte";
  import RemoveTimer from "$components/atom/button/RemoveTimer.svelte";
  import { onDestroy } from "svelte";
  import TimerWorker from "./TimerWorker.ts?worker";

  export let timer: ActorRefFrom<typeof timerCounterMachine>;

  const timerWorker = new TimerWorker();

  timerWorker.addEventListener("message", (e) => {
    if (e.data === "ONE_SECOND_ELAPSED") timer.send("ONE_SECOND_ELAPSED");
  });

  onDestroy(() => {
    timerWorker.terminate();
  });
</script>

<div
  class="border-2 border-blue-100 rounded-lg w-96 shadow shadow-blue-200 flex flex-col justify-between gap-8 duration-500 py-8">
  <TimerDisplay {timer} />
  {#if $timer.matches("new") || $timer.matches("timerSet")}
    <TimerSelectButtonCluster {timer} />
  {/if}
  <TimerControllerCluster {timer} />
  <Divider />
  <Counter {timer} />
  <Divider />
  <TimerLabel
    textToDisplay={$timer.context.timerLabel}
    on:input={(e) => {
      timer.send({
        type: "TIMER_COUNTER_LABEL_CHANGED",
        // @ts-ignore
        updatedLabel: e.target?.value ?? "",
      });
    }} />
  <RemoveTimer
    on:click={() => {
      timer.send({ type: "TIMER_COUNTER_DELETED", timerId: timer.id });
    }} />
</div>

// src/components/molecule/timer/timer-counter/TimerCounterComponent.tsx
"use client";

import { useEffect, useRef } from "react";
import { useSelector } from "@xstate/react";
import type { ActorRefFrom } from "xstate";
import type { timerCounterMachine } from "@/components/molecule/timer/timer-counter/TimerCounter";
import TimerDisplay from "@/components/atom/display/TimerDisplay";
import Divider from "@/components/atom/divider/Divider";
import Counter from "@/components/molecule/counter/Counter";
import TimerControllerCluster from "@/components/molecule/timer/TimerControllerCluster";
import TimerSelectButtonCluster from "@/components/molecule/timer/TimerSelectButtonCluster";
import TimerLabel from "@/components/atom/input/TimerLabel";
import RemoveTimer from "@/components/atom/button/RemoveTimer";

interface Props {
  timer: ActorRefFrom<typeof timerCounterMachine>;
}

export default function TimerCounter({ timer }: Props) {
  const snapshot = useSelector(timer, (s) => s);
  const workerRef = useRef<Worker | null>(null);

  useEffect(() => {
    workerRef.current = new Worker(
      new URL("./TimerWorker.ts", import.meta.url),
    );
    workerRef.current.addEventListener("message", (e) => {
      if (e.data === "ONE_SECOND_ELAPSED") {
        timer.send({ type: "ONE_SECOND_ELAPSED" });
      }
    });
    return () => {
      workerRef.current?.terminate();
    };
  }, [timer]);

  return (
    <div className="border-2 border-blue-100 rounded-lg w-96 shadow shadow-blue-200 flex flex-col justify-between gap-8 duration-500 py-8">
      <TimerDisplay timer={timer} />
      {(snapshot.matches("new") || snapshot.matches("timerSet")) && (
        <TimerSelectButtonCluster timer={timer} />
      )}
      <TimerControllerCluster timer={timer} />
      <Divider />
      <Counter timer={timer} />
      <Divider />
      <TimerLabel
        textToDisplay={snapshot.context.timerLabel}
        onCommit={(value) =>
          timer.send({
            type: "TIMER_COUNTER_LABEL_CHANGED",
            updatedLabel: value,
          })
        }
      />
      <RemoveTimer
        onClick={() =>
          timer.send({ type: "TIMER_COUNTER_DELETED", timerId: timer.id })
        }
      />
    </div>
  );
}
