// src/component/atom/button/Duration.svelte
<script lang="ts">
  import type { TimerInterval } from "$component/molecule/timer/timer-counter/TimerCounter";

  export let individualInterval: TimerInterval;
</script>

<button
  on:click
  class="text-teal-200 border-2 border-teal-300 rounded-full text-2xl w-20 h-20">
  {individualInterval.label}
</button>

// src/components/atom/button/Duration.tsx
import type { TimerInterval } from "@/components/molecule/timer/timer-counter/TimerCounter";

interface Props {
    individualInterval: TimerInterval;
    onClick: () => void;
}

export default function Duration({ individualInterval, onClick }: Props) {
    return (
        <button
            onClick={onClick}
            className="text-teal-200 border-2 border-teal-300 rounded-full text-2xl w-20 h-20"
        >
            {individualInterval.label}
        </button>
    );
}
